# Generated by Django 3.1.7 on 2021-11-21 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20211117_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='recipes_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
